name: Node-Gyp Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.7.0'  # Specify the latest LTS version explicitly
          
      - name: Install dependencies
        run: |
          npm install -g node-gyp
          npm install

      - name: Run setup script
        run: |
          chmod +x setup_node_gyp.sh
          ./setup_node_gyp.sh
